include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_relative_imports: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    sort_child_properties_last: false