
targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run
      # dart run build_runner doctor to check your config.
      freezed:freezed:
        enabled: true
        generate_for:
          - lib/modules/models/**.dart
          - lib/modules/models/**/**.dart
      
      hive_generator:hive_generator:
        enabled: true
        generate_for:
          - lib/modules/models/**.dart
          - lib/modules/models/**/**.dart
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          - lib/modules/models/**.dart
          - lib/modules/models/**/**.dart