name: audiolizer
description: The Audiolizer project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^1.0.1

  file_picker: ^4.5.1
  permission_handler: ^9.2.0

  # state management
  flutter_riverpod: ^2.0.0-dev.9
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # code generation
  freezed_annotation: ^2.1.0
  json_annotation: ^4.4.0

  # windows specific
  window_manager: ^0.2.1

  #fonts
  google_fonts: ^2.3.2

  #svg support
  flutter_svg:

  #forms
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.1
  flutter_multi_formatter: ^2.5.1

  # http requests
  dio: ^4.0.6

  #share to other apps
  share_plus: ^4.0.10+1
  receive_sharing_intent: ^1.4.5

  #database
  hive: ^2.1.0

  #get paths for OS
  path_provider: ^2.0.10
  
  file: ^6.1.2
  rxdart: ^0.27.3
  fluttertoast: ^8.0.9

  infinite_scroll_pagination: ^3.2.0

  result_type: ^0.1.0

  data_table_2: ^2.3.6
  auto_size_text: ^3.0.0

  sliding_up_panel: ^2.0.0+1
  selectable: ^0.2.4

  midi_util:
    git:
      url: https://github.com/Eghosa-Osayande/midi_util
      ref: main 
  auto_size_text_field: ^2.1.0
  flutter_slidable: ^2.0.0
  intl:
  pdf: ^3.8.3
  printing: ^5.9.2
  floating_action_bubble: ^1.1.4
  firebase_core: ^1.21.1
  firebase_analytics: ^9.3.3
  cloud_firestore: ^3.4.6
  flutter_inappwebview: ^5.4.3+7
  flutter_animate: ^1.0.0
  skeletons: ^0.0.3
  firebase_database: ^9.1.4
  cached_network_image: ^3.2.1
  scrollable_positioned_list: ^0.3.4
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

  
  bloc_test: ^9.0.2
  mocktail: ^0.3.0

  build_runner:
  freezed: ^2.1.0 
  json_serializable:
  hive_generator: ^1.1.2
  analyzer: ^4.6.0
  change_app_package_name: ^1.1.0
  
  



flutter:  
  uses-material-design: true

  assets:
    - assets/images/logo_colored.png

  fonts:
    - family: Logo
      fonts:
        - asset: assets/fonts/logo.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
